name: ipify-api

on:
  push:
    branches: [ levvels ]
  pull_request:

jobs:
  build-ipify-api:
    runs-on: ubuntu-latest

    outputs:
      digest: ${{ steps.docker_build.outputs.digest }}

    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: '1.20.1'
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build
      run: |
        go mod vendor
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/ipify-api .
    
    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/tf-dive/ipify-api
        tags: |
          type=raw,value=dev
          type=semver,pattern={{ version }}

    - name: Build image and publish to registry
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        file: ./Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          GIT_REV=${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-ipify-api
    
    steps:
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Checkout kustomize repository
        uses: actions/checkout@v2
        with:
          repository: tf-dive/kubekube-dive-devops
          ref: main
          token: ${{ secrets.PAT }}
          path: kubekube

      - name: Update Kubernetes resources
        run: |
          pwd
          echo ghcr.io/tf-dive/ipify-api@\${{ needs.build-ipify-api.outputs.digest }}
          cd kubekube/dev/recipes/ns-platform/ipify-api/overlays
          kustomize edit set image ghcr.io/tf-dive/ipify-api@\${{ needs.build-ipify-api.outputs.digest }}
          cat kustomization.yaml
      # 수정된 파일 commit & push
      - name: Commit minifest files
        run: |
          cd kubekube
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "Update ipify-api image tag(${{ needs.build-ipify-api.outputs.digest }})"
          git push -u origin main
