name: ipify-api

on:
  push:
    branches: [ levvels ]
  pull_request:

jobs:
  build-ipify-api:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: '1.20.1'
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build
      run: |
        go mod vendor
        go build -o bin/ipify-api .
    
    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/tf-dive/ipify-api
        tags: |
          type=raw,value=dev
          type=semver,pattern={{ version }}

    - name: Build image and publish to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          GIT_REV=${{ github.sha }}
